name: Workflow test

on:
  repository_dispatch:
    types: [publish-to-preview]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      run: [ $MESSAGE == 'ok' ] && exit 0 || exit 1
      env:
        MESSAGE: ${{ github.event.client_payload.message }}
    outputs:
      job-status: ${{ job.status }}

  notify:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Notify webhook
        run: |
          curl -n -X POST $NOTIFICATION_URL -H "Content-Type: application/json" -d '{ "status": "'"$BUILD_STATUS"'" }'
        env:
          BUILD_STATUS: ${{ needs.build.outputs.job-status }}
          NOTIFY_RESULT: ${{ job.status == 'success' && 'success1' || 'error1' }}
          NOTIFICATION_URL: https://webhook.site/2fb88575-8248-47e9-b8af-f3df9bbb009e
