name: Workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify webhook
        run: |
          curl -n -X POST $NOTIFICATION_URL -H "Content-Type: application/json" -d '{ "status": "'"$NOTIFY_RESULT $ACTION_STATUS"'" }'
        env:
        NOTIFY_RESULT: ${{ job.status == 'success' && 'success1' || 'error1' }}
        ACTION_STATUS: ${{ job.status }}
        NOTIFICATION_URL: https://webhook.site/2fb88575-8248-47e9-b8af-f3df9bbb009e