name: Workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify webhook
        run: |
          curl -n -X POST $NOTIFICATION_URL -H "Content-Type: application/json" -d "{ \"status\": \"$NOTIFY_RESULT $ACTION_STATUS\" }"
        env:
          ACTION_STATUS: ${{ job.status }}
          NOTIFY_RESULT: ${{ job.status == "success" && "success" || "error"}}
          NOTIFICATION_URL: https://webhook.site/2fb88575-8248-47e9-b8af-f3df9bbb009e