name: Workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notify webhook
        run: |
          curl -n -X POST https://webhook.site/2fb88575-8248-47e9-b8af-f3df9bbb009e -H 'Content-Type: application/json' -d '{ "status": "success" }'